src/utils.js

The skybox does not work in WebGL contexts after the first one created. I often need to destroy and create new gl convas', and only the first one has the skybox.
This is beacause the current code modifies the value of THREE.ShaderLib["cube"], instead of creating a new copy each time.

Fixes in the creation of the skybox.

---

src/EarthControls.js
src/OrbitControls.js

As per the comments on https://github.com/potree/potree/pull/191.  Three mouse constants are as per https://github.com/mrdoob/three.js/blob/317d6f66542ab63323c5dab6c7a4e9d08c07ca05/src/Three.js#L134

flip y axis of orbit controls and make mouse buttons explicit in code

---

examples/entwine_greyhound.html
gulpfile.js
src/PointCloudGreyhoundGeometryNode.js
src/loader/GreyhoundLoader.js

This does some simplification to the Greyhound-loader's scale/offset usage.  Also, in the sample viewer for Greyhound, resources are updated to current names, and resources can be overridden with query parameters.

Simplify scale/offset usage for Greyhound usage.

---

examples/entwine_greyhound.html
gulpfile.js
src/PointCloudGreyhoundGeometry.js
src/PointCloudGreyhoundGeometryNode.js
src/loader/GreyhoundBinaryLoader.js
src/loader/GreyhoundLoader.js
src/workers/GreyhoundBinaryDecoderWorker.js

This builds upon #283 for the Greyhound loader.  I've submitted it separately for tracking purposes, so if #283 gets nixed I will force-push over this one with these changes isolated.  The changes here are quite small but looks a bit large since I pulled the HTTP fetches into functions toward the top.
The basic idea is to check a few thousand points at the base depth, and if any of them have color or intensity values > 255, then those values will be truncated later within the decoder worker.
Some sample resources where this is necessary are `sncf` and `dk`.  For example you could use [this link locally](http://localhost:8080/examples/entwine_greyhound.html?resource=sncf), which uses 16-bit color and is all white without this PR.

Normalize color/intensity if needed for Greyhound resources

---

.jshintrc
gulpfile.js
jshint_config.js
package.json

Hey @m-schuetz,
Here's my first PR to potree :). I just added some kind of severity to jshint and indeed it detected a lot of unused variables, missing semicolons, not defined variables etc.
To launch the linter you should rerun npm install --save-dev and then 'gulp linter'
I'll be fixing the issues step by step in my spare time.
What do you think?
Thanks!

Added linter task to gulp. Added more severe rules to jshint

---

src/loader/GreyhoundLoader.js

This fixes the Greyhound code that detects when the intensity should be normalized. This is following up on https://github.com/potree/potree/commit/3fb45b6b26d4f3fb4b49d513fdd35757a2b08a80#commitcomment-21990352.

Fix Greyhound intensity normalization detection

---

package-lock.json
package.json
src/loader/PointAttributes.js

Eslint has had a version update that fixes a bug which was visible in the repo through a linting error. Since NPM on travis uses a version of NPM that doesn't support `package-lock.json` it might have fallen through the gaps during development.  This PR updates eslint and fixes the linting error.

Updated eslint and fixed linting

---

src/Annotation.js
src/viewer/Scene.js

WRT https://github.com/potree/potree/issues/394
This PR allows removal of an annotation via the Scene. It also removes all the children of that annotation when it's removed.
Thanks
Rob

Allows removal of an annotation

---

src/Annotation.js

Allows programmatic editing of the title and description of annotations, without affecting the external API of the Annotation class.

Allows editing of the annotation title and description

---

src/materials/PointCloudMaterial.js

When transparency was set lower to one, `this.depthFunc = THREE.AlwaysDepth`, but it was then not set back to `THREE.LessEqualDepth` when cloud opacity/alpha was equal to 1 again.

Oneline Hotfix for cloud transparency

---

docs/potree-file-format.md

It looks that liblas.org as moved from https://www.liblas.org to https://liblas.org without redirection
Same for laszip.org
Please follow these instructions when creating a new pull request:
* Set the potree develop branch as the PR target.
* Builds should not be part of the PR. Don't commit them. 
* Do not use a formatter. They make a mess out of diffs. 
* It takes a lot of time to download and test, as well as analyze the diffs,
so please excuse if it takes time to respond or if you don't get a response.

Update potree-file-format links

---

libs/shapefile/shapefile.js

Currently reading polylinez will fail since the record never advances over the z components of the vertices. This fixes reading these features, returning points with the additional z component.

Adding PolyLineZ support to shapefiles.

---

src/utils/Measure.js
src/utils/MeasuringTool.js
src/utils/VolumeTool.js
src/viewer/viewer.js

Add the ability to have the measure display units be different than the units used in the point cloud
The setLengthUnit() method that existed before only set the labels that display when measurements are being made.  This is great when the data happens to be in the same units that the end user thinks in.  To separate the concerns of data vs. user interface a new method setLengthUnitAndDisplayUnit(lengthUnitValue, lengthUnitDisplayValue) was created which takes two parameters: lengthUnitValue which indicates which units the data is in and lengthUnitDisplayValue which indicates which units the end user would like to see the measurements displayed in.  The legacy setLengthUnit() will still operate as it always has.
As an example, one can set the units to be display as feet when the data is …

Separate measure display units from measure data units

---

src/viewer/sidebar.js

Load the items in the classification filter in the sidebar from the classifications defined in the viewer.
In order to allow for customization of classifications, load the classifications in the filter from the one master list source of classifications.
Would this pull request be something you would consider.  Let me know.  My ultimate goal is to allow for custom (additional) classifications to be able to be used.  If there is another way to approach, please advise.   I was also wanting to make a pull request to include the color of the classification in the filter if color by classification.
The thought was that this PR would open up the ability to specify (extend) custom classifications when setting up the viewer:
```
window.viewer = new …
```

Load classification filter from viewer classifications

---

src/loader/LasLazLoader.js

when i start chrome with --allow-file-access-from-files,
it will return status 0 when i start a XMLHttpRequest for las/laz file.

xhr request support loading from file system

---

src/viewer/PropertyPanels/PropertiesPanel.js

Fix typo that leads to range clamping bug as described in potree/potree#606 and hobu/usgs-lidar#2

Fix typo. Closes potree/potree#606

---

src/ProfileRequest.js

Fixed profile viewing for EPT data.  Adds fallback logic for usage of `hierarchyStepSize`, which doesn't exist in the EPT format.

EPT profile viewing.  See connormanning/potree#2.

---

examples/deviceorientation.html
src/Potree.js

I saw you mentioned deviceorientation.html was not working in the list of high priority issues. I went to take a look and it seems like the control objects were no longer exposed in the Potree object, which the example uses to set the controls: `viewer.setNavigationMode(Potree.DeviceOrientationControls);`. Here is a quick fix for that. 
It also seems like EDL is no longer working on mobile (it does not show any point cloud with it enabled), at least not on my phone, neither using Chrome nor Samsung Internet. This does not seem to be connected to the device orientation controls though, so in this PR I just disabled EDL for this example.

Fix device orientation

---

src/PointCloudOctree.js
src/PotreeRenderer.js
src/loader/ept/LaszipLoader.js
src/materials/PointCloudMaterial.js
src/materials/shaders/pointcloud.vs
src/viewer/HQSplatRenderer.js
src/viewer/sidebar.html
src/viewer/sidebar.js
src/viewer/viewer.js
src/workers/EptLaszipDecoderWorker.js

Add Point source ID filtering, fix GPS time filtering for EPT-LAS datasets
This is an updated version of #712 to resolve merge conflicts. Closes #712 
Please note: The range filtering (GPS time, return number, etc) are not working in on `develop`, so I was not able to test the changes in this PR

Filtering improvements

---

README.md
package-lock.json
package.json

I did some minor improvements so that people familiar with NodeJS ecosystem can feel right at home and also newbies can follow standard practices without the need for global installations.
From commit message:
> Requiring global installation of any tools is not the best practice, as it can
> introduce situations when one project requires one version of e.g. gulp and
> another application requires another version. To combat that, npm provides a great
> way to encapsulate dependencies inside `node_modules` directory and includes all
> binaries in PATH whenever `npm ...` commands are ran.
> 
> In this commit, `rollup` was added as a dependency to `package.json` so that global
> installation is not required. Additionally, npm scripts for common operations were
> added: `npm start` for …

Remove requirement for global gulp and rollup

---

src/materials/shaders/pointcloud.vs

When using fixed point sizes and filtering for Level of Detail (LOD), Potree would suffer a fatal crash. 
This went unnoticed for a while because adaptive size is pretty common. Closes #798 👍 
The cause was due to inconsistent references in the point cloud vertex shader.
`color_type_lod` vs `color_type_level_of_detail`
I would have preferred using the shorter of the two, but that would have created other issues.
@m-schuetz Now that this PR is cleaned up, please review it when you get a chance.

Resolve Potree Crash When Selecting Level of Detail - Fixes #798

---

src/viewer/profile.js
src/viewer/viewer.js

This series of commits should close #807 in time for Potree 1.7 👌 
Enabling the float color buffer on the viewer and profile was simple. Also cleaned up a duplicate extension call for frag depth in profile.js.
The tricky part was pinning down the cause for this:
> THREE.Matrix3: .getInverse() can't invert matrix, determinant is 0
This comes from when the profile is first rendered, and it is always rendered upon initialization whether it has a reason to display or not due to the `resize` event listener. And as you can guess, this means that _every_ time the window is resized in some way (even an orientation change), the profile would re-render. Playing with the window size for approximately 1 second on my laptop resulted in over 100 warning messages.
So now, before we allow for a `resize` …

WebGL Improvements to Fix #807

---

src/utils.js
src/viewer/map.js

I have some EPT sources where the `projection` string that gets defined is an EPSG code string, like `EPSG:6339`. So I added a check to use that, instead of a prjo4 string in transform step when calculating azimuth.
I also added some proj4 definitions that I use frequently. Hopefully `map.js` is an okay place to do this. But happy to move or remove if necessary.

Fixing azimuth calculations on EPT sources and adding EPSG defs

---

package-lock.json
package.json
src/PointCloudEptGeometry.js
src/Potree.js
src/exporter/LASExporter.js

There are a plethora of security fixes that have been released for Potree's NPM dependencies. 
This brings down the vulnerabilities to a single (low severity) prototype pollution issue of `yargs-parser`. This seems to be something that Gulp makes brief use of. I would update this too, manually, however the current dependency requirement is for version 5.x.x, and there is only 5.0.0 available. The next newest version is 6.0.0, which is a major version change that might have breaking changes. Funny enough, that version is also vulnerable though. This script would have to be updated to version 13+ in order to not be affected. Compatibility is definitely not guaranteed for such a heroic upgrade. It would be best to let the Gulp crew manage this and update when they have verified compatibility …

Security Fixes, Prepare Package.json for Version 1.7

---

src/viewer/profile.js
src/viewer/viewer.js

This used to be the result of getting a simple height profile or clipping something - anywhere from dozens to hundreds of matrix inversion fails resulting in more processor usage and a polluted console log.
Excerpts from the commit logs.
Closes #814 **
> This patches the condition where d3 scaleX invert results in 0 radius.
> 
> When the point's scale is set to 0, 0, 0, the position becomes 0, 0, 0,
> and ultimately, all of the matrix elements become 0, which is invalid.
Closes #815 **
> This patches the condition where first 4 Matrix4 elements are 0.
> 
> This sometimes occurs with measurements. These elements will always be factored with the other elements when getInverse() is called, meaning the result will be 0 (an invalid state with no inverse).
> In these cases, ThreeJS will return …

Fixes for Matrix3 / Matrix4 .getInverse() Warnings - Clipping & Height Profiling

---

package.json

- Runs the build script after `npm install`
- References a main file so that `import { x } from 'potree'` can be used.

Add postinstall script and main property.

---

src/PotreeRenderer.js
src/modules/loader/2.0/OctreeLoader.js

This addresses the later issue in potree/PotreeConverter#457
PDAL + Converter 2.0 created a division by zero scenario for GPS Time.
The fix is to simply check for NaN after scale & offsets are set.
We reset them to sane defaults if NaN is found.
This can be fixed in a variety of ways. I just went with something quick. Let me know if the defaults need changing. I'm leaving this open to modifications, so feel free to edit something in place if needed.

Fix for Borked GPS Time / Extra Ranges

---

src/loader/POCLoader.js

Add replacements for GPS_TIME in parseAttributes func.
The lack of this entry caused an error when working with gps-time. 
I don't remember exactly where it happened but this line fixes the problem.

POCLoader, replacements for GPS_TIME

---

src/utils/MeasuringTool.js

Change from `viewer` to `this.viewer` since the first is only known in the constructor.

MeasuringTool, reference error

---

src/utils/Measure.js

This PR fixes the bug noted in [Issue #935 ](https://github.com/potree/potree/issues/935). When hovering over pointclouds with the Point Measure tool, attributes would get orphaned in the Properties Panel once the cursor moved over a pointcloud that no longer had those attributes. 
Steps to reproduce the bug prior to this PR:
1. Start the `multiple_pointclouds.html` example
2. Start a Point Measure and hover over a lion, then the landscape
3. You will see that the normals attributes from the lion remain in the Properties Panel, but no longer update because the landscape does not have normals
The fixed behavior in this PR:
Hovering from the lion back to the landscape causes the normals attributes to disappear from the Properties Panel.

Fix Orphaned Attributes in Properties Panel
